allowBuilds:
  esbuild: true
  msw: true
minimumReleaseAgeExclude:
  - '@xterm/addon-clipboard@0.3.0-beta.292'
  - '@xterm/addon-fit@0.12.0-beta.292'
  - '@xterm/addon-search@0.17.0-beta.292'
  - '@xterm/addon-serialize@0.15.0-beta.292'
  - '@xterm/addon-unicode11@0.10.0-beta.292'
  - '@xterm/addon-web-links@0.13.0-beta.292'
  - '@xterm/addon-webgl@0.20.0-beta.291'
  - '@xterm/xterm@6.1.0-beta.292'
