/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NextermIconButton: typeof import('./components/NextermIconButton.vue')['default']
    TooltipTitle: typeof import('./components/TooltipTitle.vue')['default']
    WindowControls: typeof import('./components/WindowControls.vue')['default']
  }
}
